# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4215c5821122de56f50050161ed4d66b6f160a847b9329dfbfe90c0a45d7c8eb27393e0901f1f0ab4a7208e9536e0c46d523c32d69d7936edb379c9a6f5b119d

test:
  secret_key_base: 677bd8013ce42a2e0107885f3345f4cd20232b3519a61025aa14fdecf6867b0f315f67ec04b69773ef953dcd956a4c4bc27a6fb0ff89107bd3c57449a45be7bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
